on:
  pull_request:
    branches:
      - master
    # types: [closed]

jobs:
  backport:
    name: Backport
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install -g backport

      - name: Labels
        run: |
          echo "$PR_LABELS"
        env:
          PR_LABELS: ${{ toJSON(github.event.pull_request.labels) }}

      # Switch to master?

      - name: backport
        run: backport --username "${{ github.actor }}" --accessToken "${{ secrets.GITHUB_TOKEN }}" --dryRun --ci --pr "28" --labels backport --verbose --upstream "brianseeders/kibana"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
